# Generated by Django 4.2 on 2023-06-15 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyLoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desiredAmount', models.IntegerField(verbose_name='Amount')),
                ('dateApplied', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=10)),
                ('dateDecision', models.DateField(blank=True, null=True, verbose_name='Date Resolve')),
            ],
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=50, verbose_name='First Name')),
                ('lName', models.CharField(max_length=50, verbose_name='Last Name')),
                ('joinOn', models.DateField(auto_now_add=True)),
                ('uname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0.0, verbose_name='Amount')),
                ('paidDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Repayment', 'Repayment'), ('Paid', 'Paid')], default='Repayment', max_length=50)),
                ('comment', models.TextField()),
                ('loanAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.applyloanrequest')),
                ('receivingBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.managers')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.applyloanrequest')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.member')),
            ],
        ),
        migrations.AddField(
            model_name='managers',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.member'),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=500.0)),
                ('paidOn', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.member')),
                ('receivedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseApp.managers')),
            ],
        ),
        migrations.AddField(
            model_name='applyloanrequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseApp.managers'),
        ),
        migrations.AddField(
            model_name='applyloanrequest',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.member'),
        ),
    ]
