# Generated by Django 4.2 on 2023-06-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_alter_message_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyloanrequest',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
